---
abstract: 'Candy for Perl programming in Vim'
author:
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  File::Spec: '0'
  File::Which: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.3601'
  Test::Class::Moose: '0'
  Test::Class::Moose::Load: '0'
  Test::More: '0.88'
  base: '0'
  perl: '5.006'
configure_requires:
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.014, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Vim-X
provides:
  Vim::X:
    file: lib/Vim/X.pm
    version: v0.3.0
  Vim::X::Buffer:
    file: lib/Vim/X/Buffer.pm
    version: v0.3.0
  Vim::X::Line:
    file: lib/Vim/X/Line.pm
    version: v0.3.0
  Vim::X::Plugin::ResolveConflict:
    file: lib/Vim/X/Plugin/ResolveConflict.pm
    version: v0.3.0
  Vim::X::Window:
    file: lib/Vim/X/Window.pm
    version: v0.3.0
requires:
  Carp: '0'
  Exporter: '0'
  Moo: '0'
  Path::Tiny: '0'
  Sub::Attribute: '0'
  overload: '0'
  parent: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/yanick/Vim-X/issues
  homepage: http://search.cpan.org/dist/Vim-X/
  repository: https://github.com/yanick/Vim-X.git
version: 0.3.0
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
x_contributors:
  - 'Hernan Lopes <aut_hlopes@uolinc.com>'
